{% set name = "pydocstyle" %}
{% set version = "4.0.1" %}
{% set hash_type = "sha256" %}
{% set hash = "04c84e034ebb56eb6396c820442b8c4499ac5eb94a3bda88951ac3dc519b6058" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
    script: python setup.py install --single-version-externally-managed --record=record.txt
    number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six
    - snowballstemmer
    - configparser  # [py2k]

test:
  imports:
    - pydocstyle

about:
  home: https://github.com/PyCQA/pydocstyle
  license: MIT
  summary: 'Python docstring style checker (formerly pep257)'
  description: |
    pydocstyle is a static analysis tool for checking compliance with Python
    docstring conventions. pydocstyle supports most of PEP 257 out of the box,
    but it should not be considered a reference implementation.
    The framework for checking docstring style is flexible, and custom checks
    can be easily added, for example to cover NumPy docstring conventions.
    pydocstyle supports Python 2.6, 2.7, 3.3, 3.4, 3.5, pypy and pypy3.
  doc_url: http://pydocstyle.readthedocs.org
  dev_url: https://github.com/PyCQA/pydocstyle

extra:
  recipe-maintainers:
    - goanpeca
    - jakirkham
    - Nurdok
    - dopplershift
